/*Creation of table REGLAS_NOMBRE_PLAN*/
CREATE TABLE REGLAS_NOMBRE_PLAN
(
	COD_REGLAS_NOMBRE_PLAN  	int 	NOT NULL,
	COD_PRODUCTO 	 			int,
	COD_SERVICIO  				int,
	NOMBRE_PLAN  				varchar(100),
	APLICA_VELOCIDAD  			int,
	ARRENDAMIENTO  				int,
	RELACIONADO_TI 				int,
	ST_ELIM						bit
);

/*Creation of table TMPROD_PADRE*/
CREATE TABLE TMPROD_PADRE(
	COD_PROD_PADRE			 	int 		NOT NULL,
	DESC_PROD_PADRE				varchar(50) NULL,
	ST_ELIM						bit,
	CO_USUA_CREO				smallint,
	CO_USUA_MODI				smallint,
	FH_CREO						datetime,
	FH_MODI						datetime
);

/*Creation of table TMPROD_PADRE_TMPROD*/
CREATE TABLE TMPROD_PADRE_TMPROD 
(
	COD_PROD_PADRE_PROD 		int 	NOT NULL IDENTITY(1,1),
	COD_PROD_PADRE 				int 	NOT NULL,
	COD_PROD 					tinyint NOT NULL
);

/*Creation of table TMCONFIGURACION_FECHAS*/
CREATE TABLE TMCONFIGURACION_FECHAS(
	COD_CONFIGURACION_FECHAS 	int 	NOT NULL,
	COD_PRODUCTO 				int,
	FECHA_INICIO 				int,
	FECHA_FIN 					int
);

--CREATE TABLE TMTABLA_TABLAS
--(
--  ID_TABLAS             INT NOT NULL,
--  NOMBRE                VARCHAR(100),
--  DESCRIPCION           VARCHAR(500),
--  ID_TABLA_PADRE        INT,
--  CODIGO                VARCHAR(50),
--  VALOR1                VARCHAR(100),
--  VALOR2                VARCHAR(100),
--  TIPO                  VARCHAR(25),
--  CONFIGURABLE			BIT,
--  ESTADO                INT,
--  CO_USUA_CREO      	VARCHAR(8),
--  FH_CREO      			DATETIME,
--  CO_USUA_MODI 			VARCHAR,
--  FH_MODI 				DATETIME
--  
--);


CREATE TABLE TMBOLE(
	CO_BOLE 			bigint NOT NULL,
	CO_CIER 			int NOT NULL,
	CO_NEGO 			int NOT NULL,
	DE_PERI 			varchar(200) NOT NULL,
	IM_NETO 			decimal(12, 2) NOT NULL,
	IM_AJUS_SIGV 		decimal(12, 2) NOT NULL,
	IM_IGV 				decimal(12, 2) NOT NULL,
	IM_TOTA 			decimal(12, 2) NOT NULL,
	IM_AJUS_NIGV 		decimal(12, 2) NOT NULL,
	IM_INST 			decimal(12, 2) NOT NULL,
	IM_SERV_MENS 		decimal(12, 2) NOT NULL,
	IM_ALQU 			decimal(12, 2) NOT NULL,
	IM_OTRO 			decimal(12, 2) NOT NULL,
	IM_DESC 			decimal(12, 2) NOT NULL,
	IM_DIF_CARGO_FIJO 	decimal(12, 2) NOT NULL,
	ST_ANUL 			bit NOT NULL DEFAULT ((0)),
	ST_ELIM 			bit NULL DEFAULT ((0)),
	FE_EMIS 			date NOT NULL,
	FE_VENC 			date NOT NULL,
	CO_CLIE 			int NOT NULL,
	DE_CODI_BUM 		varchar(20) NULL,
	NO_CLIE 			varchar(100) NOT NULL,
	DE_DIRE_FISC 		varchar(200) NOT NULL,
	CO_DIST_FISC 		int NOT NULL,
	NO_DIST_FISC 		varchar(50) NOT NULL,
	CO_TIPO_DOCU 		tinyint NOT NULL,
	NO_TIPO_DOCU 		varchar(50) NOT NULL,
	DE_NUME_DOCU 		char(30) NOT NULL,
	DE_DIRE_CORR 		varchar(200) NOT NULL,
	DE_REF_DIRE_CORR 	varchar(200) NULL,
	CO_DIST_CORR 		int NOT NULL,
	NO_DIST_CORR 		varchar(50) NOT NULL,
	DE_DIRE_INST 		varchar(200) NOT NULL,
	CO_DIST_INST 		int NOT NULL,
	NO_DIST_INST 		varchar(50) NOT NULL,
	CO_MONE_FACT 		tinyint NOT NULL,
	NO_MONE_FACT 		varchar(30) NOT NULL,
	DE_SIMB_MONE_FACT 	char(5) NOT NULL,
	CO_USUA_CREO 		smallint NULL,
	CO_USUA_MODI 		smallint NULL,
	FH_CREO 			datetime NULL,
	FH_MODI 			datetime NULL,
	FE_INI 				date NULL,
	FE_FIN 				date NULL
);

/*Add Column*/
ALTER TABLE TMFACT_GLOS 			ADD TI_GLOS 		INT 			NOT NULL;
ALTER TABLE TMFACT_GLOS 			ADD DE_DIRE_SUCU 	VARCHAR(200)  	NULL;
ALTER TABLE TMFACT_GLOS 			ADD CO_DIST 		INT  			NULL;
ALTER TABLE TMFACT_GLOS 			ADD NO_DIST 		VARCHAR(50)  	NULL;
ALTER TABLE TMPLAN_MEDI_INST 		ADD COD_PROD_PADRE 	INT  			NULL;  
ALTER TABLE TMPLAN 					ADD RELACIONADO_TI 	BIT DEFAULT 0 	NOT NULL;
ALTER TABLE TMNEGO 					ADD REFERENCIA 		VARCHAR(150) 	NULL;  
ALTER TABLE TMNEGO_SUCU 			ADD REFERENCIA 		VARCHAR(150) 	NULL;

ALTER TABLE TMCIER_DATA_PLAN 		ADD CO_BOLE 		BIGINT 			NULL; 
ALTER TABLE TMCIER_DATA_PROM_MONT 	ADD CO_BOLE 		BIGINT 			NULL; 
ALTER TABLE TMCIER_DATA_SERV_SUPL 	ADD CO_BOLE 		BIGINT 			NULL; 
ALTER TABLE TMCIER_DATA_SERV_UNIC 	ADD CO_BOLE 		BIGINT 			NULL; 
ALTER TABLE TMRECI_GLOS 			ADD CO_BOLE 		BIGINT 			NULL; 
ALTER TABLE TMCIER		 			ADD DE_RAIZ_BOLE	BIGINT 			NULL; 
ALTER TABLE REGLAS_NOMBRE_PLAN 		ADD PRODUCTO_CARGA 	VARCHAR(25)		NULL;

ALTER TABLE TMFACT					ADD IM_AJUS_SIGV 		DECIMAL(12, 2) 		NULL;
ALTER TABLE TMFACT					ADD DE_PERI 			VARCHAR(200) 		NULL;
ALTER TABLE TMFACT					ADD IM_SERV_MENS 		DECIMAL(12, 2) 		NULL;
ALTER TABLE TMFACT					ADD IM_DIF_CARGO_FIJO 	DECIMAL(12, 2) 		NULL;
ALTER TABLE TMFACT					ADD FE_INI 				DATE 				NULL;
ALTER TABLE TMFACT					ADD FE_FIN 				DATE 				NULL;

ALTER TABLE TMNEGO					ADD DE_DIRE_FISC 		VARCHAR(500) 		NULL;


/*Alter Column*/
ALTER TABLE TMRECI_GLOS 			ALTER COLUMN CO_RECI BIGINT 						NULL;

ALTER TABLE TMRECI					ALTER COLUMN DE_DIRE_FISC 		VARCHAR(500) 		NULL;
ALTER TABLE TMRECI					ALTER COLUMN DE_DIRE_CORR 		VARCHAR(500) 		NULL;
ALTER TABLE TMRECI					ALTER COLUMN DE_REF_DIRE_CORR 	VARCHAR(500) 		NULL;
ALTER TABLE TMRECI					ALTER COLUMN DE_DIRE_INST 		VARCHAR(500) 		NULL;

ALTER TABLE TMFACT					ALTER COLUMN DE_DIRE_FISC 		VARCHAR(500) 		NULL;
ALTER TABLE TMFACT					ALTER COLUMN DE_DIRE_CORR 		VARCHAR(500) 		NULL;
ALTER TABLE TMFACT					ALTER COLUMN DE_REF_DIRE_CORR 	VARCHAR(500) 		NULL;
ALTER TABLE TMFACT					ALTER COLUMN DE_DIRE_INST 		VARCHAR(500) 		NULL;

ALTER TABLE TMBOLE 					ALTER COLUMN DE_DIRE_FISC 		VARCHAR(500) 		NULL;
ALTER TABLE TMBOLE 					ALTER COLUMN DE_DIRE_CORR 		VARCHAR(500) 		NULL;
ALTER TABLE TMBOLE 					ALTER COLUMN DE_REF_DIRE_CORR 	VARCHAR(500) 		NULL;
ALTER TABLE TMBOLE 					ALTER COLUMN DE_DIRE_INST 		VARCHAR(500) 		NULL;

ALTER TABLE TMRECI_GLOS				ALTER COLUMN DE_DIRE_SUCU 		VARCHAR(500) 		NULL;
ALTER TABLE TMFACT_GLOS				ALTER COLUMN DE_DIRE_SUCU 		VARCHAR(500) 		NULL;

ALTER TABLE TMCIER_DATA_SUCU		ALTER COLUMN DE_DIRE_SUCU 		VARCHAR(500) 		NULL;



/*Creation of Constraint Primary Key*/
ALTER TABLE REGLAS_NOMBRE_PLAN 		ADD CONSTRAINT PK_cod_reglas_nombre_plan 	PRIMARY KEY (COD_REGLAS_NOMBRE_PLAN);
ALTER TABLE TMPROD_PADRE 			ADD CONSTRAINT PK_cod_prod_padre		 	PRIMARY KEY (COD_PROD_PADRE);
ALTER TABLE TMPROD_PADRE_TMPROD 	ADD CONSTRAINT PK_cod_prod_padre_prod 		PRIMARY KEY (COD_PROD_PADRE_PROD);
ALTER TABLE TMCONFIGURACION_FECHAS 	ADD CONSTRAINT PK_cod_configuracion_fechas 	PRIMARY KEY (COD_CONFIGURACION_FECHAS);

ALTER TABLE TMBOLE 					ADD CONSTRAINT PK_co_bole 					PRIMARY KEY (CO_BOLE);
--ALTER TABLE TMBOLE_GLOS 			ADD CONSTRAINT PK_co_bole_glos 				PRIMARY KEY (CO_BOLE_GLOS);

/*Creation of Foreign Key*/
ALTER TABLE TMFACT_GLOS 			ADD CONSTRAINT fk_tipo_glosa 				FOREIGN KEY (TI_GLOS) 		REFERENCES TMTIPO_GLOS(CO_TIPO_GLOS);
ALTER TABLE TMPROD_PADRE_TMPROD 	ADD CONSTRAINT fk_cod_prod_padre 			FOREIGN KEY (COD_PROD_PADRE)REFERENCES TMPROD_PADRE(COD_PROD_PADRE);
ALTER TABLE TMPROD_PADRE_TMPROD 	ADD CONSTRAINT fk_cod_prod 					FOREIGN KEY (COD_PROD) 		REFERENCES TMPROD(CO_PROD);

ALTER TABLE TMCIER_DATA_PLAN 	 	ADD CONSTRAINT fk_cdp_co_bole 				FOREIGN KEY (CO_BOLE) 		REFERENCES TMBOLE(CO_BOLE);
ALTER TABLE TMCIER_DATA_PROM_MONT 	ADD CONSTRAINT fk_cdpm_co_bole  			FOREIGN KEY (CO_BOLE) 		REFERENCES TMBOLE(CO_BOLE);
ALTER TABLE TMCIER_DATA_SERV_SUPL 	ADD CONSTRAINT fk_cdss_co_bole  			FOREIGN KEY (CO_BOLE) 		REFERENCES TMBOLE(CO_BOLE);
ALTER TABLE TMCIER_DATA_SERV_UNIC 	ADD CONSTRAINT fk_cdsu_co_bole  			FOREIGN KEY (CO_BOLE) 		REFERENCES TMBOLE(CO_BOLE);

ALTER TABLE TMBOLE				 	ADD CONSTRAINT fk_co_clie  					FOREIGN KEY (CO_CLIE) 		REFERENCES TMCLIE(CO_CLIE);
ALTER TABLE TMBOLE				 	ADD CONSTRAINT fk_co_cier  					FOREIGN KEY (CO_CIER) 		REFERENCES TMCIER(CO_CIER);
ALTER TABLE TMBOLE				 	ADD CONSTRAINT fk_co_nego  					FOREIGN KEY (CO_NEGO) 		REFERENCES TMNEGO(CO_NEGO);