/*Insertando Modulo (tmitem_modu)*/
INSERT INTO TMITEM_MODU		 VALUES	(18,'Mantenimiento Factura','CIER.MantenimientoFactura',0);
INSERT INTO TMITEM_MODU		 VALUES	(18,'Mantenimiento Boleta','CIER.MantenimientoBoleta',0);

/*Insertando Relacion Modulo Perfil (tmperf_item_modu)*/
INSERT INTO TMPERF_ITEM_MODU VALUES	(1,48,0);
INSERT INTO TMPERF_ITEM_MODU VALUES	(2,48,0);
INSERT INTO TMPERF_ITEM_MODU VALUES	(4,48,0);
INSERT INTO TMPERF_ITEM_MODU VALUES	(1,49,0);
INSERT INTO TMPERF_ITEM_MODU VALUES	(2,49,0);
INSERT INTO TMPERF_ITEM_MODU VALUES	(4,49,0);



/*Insertando Productos (TMPROD_padre)*/
INSERT INTO TMPROD_PADRE VALUES (1,'Satelital'					,0,null,null,null,null); 
INSERT INTO TMPROD_PADRE VALUES (2,'ID AD EMPRESAS'				,0,null,null,null,null); 
INSERT INTO TMPROD_PADRE VALUES (3,'MIGRACION INGENIO'			,0,null,null,null,null);
INSERT INTO TMPROD_PADRE VALUES (4,'TI'							,0,null,null,null,null); 
INSERT INTO TMPROD_PADRE VALUES (5,'ID AD MAYORISTA'			,0,null,null,null,null); 
 

/*Insertando Servicios (TMPROD)*/
/*Insertando Servicios para Producto Satelital*/
--INSERT INTO TMPROD VALUES (1,2,1,'Cargos Fijos Satelital - INTERNET',0,NULL,NULL,NULL,NULL); 
--INSERT INTO TMPROD VALUES (1,2,1,'Cargos Fijos Satelital - DATOS',0,NULL,NULL,NULL,NULL);

/*Insertando Servicios para Producto Empresa*/
INSERT INTO TMPROD VALUES (1,2,1,'Internet Dedicado'			,0,NULL,NULL,NULL,NULL); 
INSERT INTO TMPROD VALUES (1,2,1,'Datos Dedicados'				,0,NULL,NULL,NULL,NULL);

/*Insertando Servicios para Producto Ingenio*/
INSERT INTO TMPROD VALUES (1,2,1,'Internet Migración Ingenio'	,0,NULL,NULL,NULL,NULL); 
INSERT INTO TMPROD VALUES (1,2,1,'Datos Migración Ingenio'		,0,NULL,NULL,NULL,NULL); 

/*Insertando Servicios para Producto TI*/
INSERT INTO TMPROD VALUES (1,2,1,'TI-Housing'					,0,NULL,NULL,NULL,NULL); 
INSERT INTO TMPROD VALUES (1,2,1,'TI-IAAS'						,0,NULL,NULL,NULL,NULL); 
INSERT INTO TMPROD VALUES (1,2,1,'TI-SAAS-CB'					,0,NULL,NULL,NULL,NULL); 
INSERT INTO TMPROD VALUES (1,2,1,'TI-SAAS-SAS'					,0,NULL,NULL,NULL,NULL); 
INSERT INTO TMPROD VALUES (1,2,1,'TI - HOU - ONE SHOT'			,0,NULL,NULL,NULL,NULL);

/*Insertando Servicios para Producto Mayorista*/
INSERT INTO TMPROD VALUES (1,2,1,'Internet Dedicados Mayorista'	,0,NULL,NULL,NULL,NULL); 
INSERT INTO TMPROD VALUES (1,2,1,'Datos Dedicado Mayorista'		,0,NULL,NULL,NULL,NULL);
INSERT INTO TMPROD VALUES (1,2,1,'Ducteria'						,0,NULL,NULL,NULL,NULL);
INSERT INTO TMPROD VALUES (1,2,1,'Colocacion'					,0,NULL,NULL,NULL,NULL);
INSERT INTO TMPROD VALUES (1,2,1,'Otros Servicios'				,0,NULL,NULL,NULL,NULL);

/*Insertando Servicios Adicional para Producto Empresa*/
INSERT INTO TMPROD VALUES (1,2,1,'Servicio de Hosting Compartido',0,NULL,NULL,NULL,NULL);--add Servicio de Hosting Compartido 30/11/2017


/*Insertando Servicios para Producto (TMPROD_PADRE_TMPROD)*/
INSERT INTO TMPROD_PADRE_TMPROD VALUES (1,1);
INSERT INTO TMPROD_PADRE_TMPROD VALUES (1,2);
INSERT INTO TMPROD_PADRE_TMPROD VALUES (2,3);
INSERT INTO TMPROD_PADRE_TMPROD VALUES (2,4);
INSERT INTO TMPROD_PADRE_TMPROD VALUES (3,5);
INSERT INTO TMPROD_PADRE_TMPROD VALUES (3,6);
INSERT INTO TMPROD_PADRE_TMPROD VALUES (4,7);
INSERT INTO TMPROD_PADRE_TMPROD VALUES (4,8);
INSERT INTO TMPROD_PADRE_TMPROD VALUES (4,9);
INSERT INTO TMPROD_PADRE_TMPROD VALUES (4,10);
INSERT INTO TMPROD_PADRE_TMPROD VALUES (4,11);
INSERT INTO TMPROD_PADRE_TMPROD VALUES (5,12);
INSERT INTO TMPROD_PADRE_TMPROD VALUES (5,13);
INSERT INTO TMPROD_PADRE_TMPROD VALUES (5,14);
INSERT INTO TMPROD_PADRE_TMPROD VALUES (5,15);
INSERT INTO TMPROD_PADRE_TMPROD VALUES (5,16);
INSERT INTO TMPROD_PADRE_TMPROD VALUES (2,17); --add Servicio de Hosting Compartido 30/11/2017

/*Insertando Registros de Cierre(tmcier)*/
--Empres
INSERT INTO TMCIER 	VALUES (3, 12,2017,3.20,'1','1','2017-12-06','2017-12-24',1,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL);
INSERT INTO TMCIER 	VALUES (4, 12,2017,3.20,'1','1','2017-12-06','2017-12-24',1,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL);
--Ingenio                                                                                               
INSERT INTO TMCIER 	VALUES (5, 12,2017,3.20,'1','1','2017-12-06','2017-12-24',1,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL);
INSERT INTO TMCIER 	VALUES (6, 12,2017,3.20,'1','1','2017-12-06','2017-12-24',1,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL);
--TI                                                                                                 
INSERT INTO TMCIER 	VALUES (7, 12,2017,3.20,'1','1','2017-12-06','2017-12-24',1,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL);
INSERT INTO TMCIER 	VALUES (8, 12,2017,3.20,'1','1','2017-12-06','2017-12-24',1,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL);	
INSERT INTO TMCIER 	VALUES (9, 12,2017,3.20,'1','1','2017-12-06','2017-12-24',1,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL);
INSERT INTO TMCIER 	VALUES (10,12,2017,3.20,'1','1','2017-12-06','2017-12-24',1,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL);
--Mayorista                                                                                              
INSERT INTO TMCIER 	VALUES (11,12,2017,3.20,'1','1','2017-12-06','2017-12-24',1,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL);
INSERT INTO TMCIER 	VALUES (12,12,2017,3.20,'1','1','2017-12-06','2017-12-24',1,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL);
INSERT INTO TMCIER 	VALUES (13,12,2017,3.20,'1','1','2017-12-06','2017-12-24',1,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL);
INSERT INTO TMCIER 	VALUES (14,12,2017,3.20,'1','1','2017-12-06','2017-12-24',1,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL);
INSERT INTO TMCIER 	VALUES (15,12,2017,3.20,'1','1','2017-12-06','2017-12-24',1,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL);
INSERT INTO TMCIER 	VALUES (16,12,2017,3.20,'1','1','2017-12-06','2017-12-24',1,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL);
                                                                       
INSERT INTO TMCIER 	VALUES (17,12,2017,3.20,'1','1','2017-12-06','2017-12-24',1,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL); --add Servicio de Hosting Compartido 30/11/2017

/*Inserting data REGLAS_NOMBRE_PLAN*/

INSERT INTO  REGLAS_NOMBRE_PLAN VALUES (1,1,1,'INTERNET SATELITAL'									,1,0,0,0,'IPB - SAT' 		);
INSERT INTO  REGLAS_NOMBRE_PLAN VALUES (2,1,1,'ARRENDAMIENTO DE EQUIPOS - INTERNET SATELITAL'		,1,1,0,0,'IPB SAT - BU' 	);
INSERT INTO  REGLAS_NOMBRE_PLAN VALUES (3,1,2,'ENLACE DE DATOS SATELITAL'							,1,0,0,0,'ADD - SAT' 		);
INSERT INTO  REGLAS_NOMBRE_PLAN VALUES (4,1,2,'ARRENDAMIENTO DE EQUIPOS - ENLACE DE DATOS SATELITAL',1,1,0,0,'ADD SAT - BU' 	);             
INSERT INTO  REGLAS_NOMBRE_PLAN VALUES (5,2,3,'DIGITAL BUSINESS INTERNET'							,1,0,0,0,'IPB' 				);
INSERT INTO  REGLAS_NOMBRE_PLAN VALUES (6,2,4,'DIGITAL BUSINESS ACCESS' 							,1,0,0,0,'ADD' 				);
INSERT INTO  REGLAS_NOMBRE_PLAN VALUES (7,2,3,'DIGITAL BUSINESS INTERNET'							,1,0,1,0,'IPB (ICX-TI)' 	);
INSERT INTO  REGLAS_NOMBRE_PLAN VALUES (8,2,4,'DIGITAL BUSINESS ACCESS' 							,1,0,1,0,'ADD (ICX-TI)' 	);								
INSERT INTO  REGLAS_NOMBRE_PLAN VALUES (9,3,5,'INTERNET SATELITAL'									,1,0,0,0,'IPB SAT - INGENIO');
INSERT INTO  REGLAS_NOMBRE_PLAN VALUES (10,3,6,'ENLACE DE DATOS SATELITAL' 							,1,0,0,0,'ADD SAT -INGENIO' );			
INSERT INTO  REGLAS_NOMBRE_PLAN VALUES (11,4,7,'SERVICIO DE HOUSING'								,0,0,0,0,'HOU' 				);
INSERT INTO  REGLAS_NOMBRE_PLAN VALUES (12,4,8,'HOSTING ONDEMAND (IAAS)'							,0,0,0,0,'IAAS' 			);
INSERT INTO  REGLAS_NOMBRE_PLAN VALUES (13,4,9,'SERVICIO DE CLOUD BACK UP'							,0,0,0,0,'SAAS - CB' 		);
INSERT INTO  REGLAS_NOMBRE_PLAN VALUES (14,4,10,'SERVICIOS ONDEMAND (SAAS)'							,0,0,0,0,'SAAS - SAS' 		);
INSERT INTO  REGLAS_NOMBRE_PLAN VALUES (15,4,11,'ONE - SHOT'										,0,0,0,0,'HOU - ONE SHOT' 	);								
INSERT INTO  REGLAS_NOMBRE_PLAN VALUES (16,5,12,'DIGITAL BUSINESS INTERNET'							,1,0,0,0,'IPB - WHO' 		); 
INSERT INTO  REGLAS_NOMBRE_PLAN VALUES (17,5,13,'DIGITAL BUSINESS ACCESS'							,1,0,0,0,'ADD - WHO' 		);
INSERT INTO  REGLAS_NOMBRE_PLAN VALUES (18,5,13,'ARRENDAMIENTO DE FIBRA OSCURA' 					,0,0,0,0,'ADD - WHO(FO)'	);
INSERT INTO  REGLAS_NOMBRE_PLAN VALUES (19,5,14,'SERVICIO DE DUCTERIA'								,0,0,0,0,'DUC - WHO' 		);
INSERT INTO  REGLAS_NOMBRE_PLAN VALUES (20,5,14,'SERVICIO DE CABLEADO'								,0,0,0,0,'DUC - WHO(SS)' 	);
INSERT INTO  REGLAS_NOMBRE_PLAN VALUES (21,5,15,'SERVICIO DE ALOJAMIENTO'							,0,0,0,0,'COL - WHO' 		);
INSERT INTO  REGLAS_NOMBRE_PLAN VALUES (22,5,16,'SERVICIO DE CROSSCONEXION'							,0,0,0,0,'OTH - WHO' 		);
INSERT INTO  REGLAS_NOMBRE_PLAN VALUES (23,5,16,'OTROS SERVICIOS TECNICOS POST VENTA'				,0,0,0,0,'OTH - WHO(SS)' 	);
INSERT INTO  REGLAS_NOMBRE_PLAN VALUES (24,5,16,'CAPACIDAD DE INTERCONEXIÓN'						,0,0,0,0,'ICX - WHO' 		);
INSERT INTO  REGLAS_NOMBRE_PLAN VALUES (25,2,4,'ARRENDAMIENTO DE INFRAESTRUCTURA' 					,0,0,0,0,'ADD - FO' 		);
INSERT INTO  REGLAS_NOMBRE_PLAN VALUES (26,2,17,'SERVICIO DE HOSTING COMPARTIDO'					,0,0,0,0,'HOS' 				);--add Servicio de Hosting Compartido 30/11/2017


/*Inserting data TMCONFIGURACION_FECHAS*/
INSERT INTO TMCONFIGURACION_FECHAS VALUES(1,1,1,5);
INSERT INTO TMCONFIGURACION_FECHAS VALUES(2,2,1,5);
INSERT INTO TMCONFIGURACION_FECHAS VALUES(3,3,1,6);
INSERT INTO TMCONFIGURACION_FECHAS VALUES(4,4,1,6);
INSERT INTO TMCONFIGURACION_FECHAS VALUES(5,5,1,7);


/*Inserting data TABLA_TABLAS*/
--INSERT INTO TMTABLA_TABLAS (ID_TABLAS,NOMBRE,DESCRIPCION,ID_TABLA_PADRE,CODIGO,VALOR1,VALOR2,TIPO,CONFIGURABLE,ESTADO,CO_USUA_CREO,FH_CREO,CO_USUA_MODI,FH_MODI)
--VALUES (1, 'parametros', 'Tabla de Parametros', NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL);
--INSERT INTO TMTABLA_TABLAS (ID_TABLAS,NOMBRE,DESCRIPCION,ID_TABLA_PADRE,CODIGO,VALOR1,VALOR2,TIPO,CONFIGURABLE,ESTADO,CO_USUA_CREO,FH_CREO,CO_USUA_MODI,FH_MODI)
--VALUES (2, 'procesando', 'Indica si se esta procesando el cierre del periodo', 1, NULL, '1', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL);