/*Inserting data TMPLAN_MEDI_INST*/

INSERT INTO TMPLAN_MEDI_INST VALUES ('MEDIOS DE INST EMPRESA',0,NULL,NULL,NULL,NULL,2);
INSERT INTO TMPLAN_MEDI_INST VALUES ('MEDIOS DE INST TI',0,NULL,NULL,NULL,NULL,4);
INSERT INTO TMPLAN_MEDI_INST VALUES ('MEDIOS DE INST MAYORISTA',0,NULL,NULL,NULL,NULL,5);







 
