INSERT INTO [GAF_FACTURACION].[dbo].[TMPROV] (NO_PROV,CO_DEPA) VALUES ('NONE','1'),
('#N/A','2'),
('ABANCAY','5'),
('ACOBAMBA','10'),
('ALTO AMAZONAS','17'),
('ANDAHUAYLAS','5'),
('ANGARAES','10'),
('ANTABAMBA','5'),
('ANTONIO RAYMONDI','4'),
('AREQUIPA','6'),
('ASCOPE','14'),
('ATALAYA','26'),
('AYABACA','21'),
('AYMARAES','5'),
('AZÁNGARO','22'),
('BAGUA','3'),
('BARRANCA','16'),
('BOLOGNESI','4'),
('CAJAMARCA','8'),
('CALCA','9'),
('CALLAO','16'),
('CAMANÁ','6'),
('CANAS','9'),
('CANCHIS','9'),
('CANGALLO','7'),
('CAÑETE','16'),
('CARABAYA','22'),
('CARAVELI','6'),
('CARHUAZ','4'),
('CASMA','4'),
('CASTILLA','6'),
('CASTROVIRREYNA','10'),
('CAYLLOMA','6'),
('CELENDÍN','8'),
('CHACHAPOYAS','3'),
('CHANCHAMAYO','13'),
('CHEPÉN','14'),
('CHICLAYO','15'),
('CHINCHA','12'),
('CHINCHEROS','5'),
('CHUMBIVILCAS','9'),
('CHUPACA','13'),
('CONDESUYOS','6'),
('CONTRALMIRANTE VILLAR','25'),
('CORONEL PORTILLO','26'),
('COTABAMBAS','5'),
('CUSCO','9'),
('CUTERVO','8'),
('DATEM DEL MARAÑON','17'),
('ESPINAR','9'),
('GRAN CHIMÚ','14'),
('HUALGAYOC','8'),
('HUAMALÍES','11'),
('HUANCA SANCOS','7'),
('HUANCABAMBA','21'),
('HUANCAVELICA','10'),
('HUANCAYO','13'),
('HUANUCO','11'),
('HUARAL','16'),
('HUARAZ','4'),
('HUARI','4'),
('HUARMEY','4'),
('HUAROCHIRI','16'),
('HUAURA','16'),
('HUAYLAS','4'),
('HUAYTARA','10'),
('ICA','12'),
('ILO','19'),
('ISLAY','6'),
('JAÉN','8'),
('JORGE BASADRE','24'),
('JUNÍN','13'),
('LA CONVENCION','9'),
('LA MAR','7'),
('LAMBAYEQUE','15'),
('LAMPA','22'),
('LAURICOCHA','11'),
('LEONCIO PRADO','11'),
('LIMA','16'),
('LORETO','17'),
('LUCANAS','7'),
('MARISCAL NIETO','19'),
('MAYNAS','17'),
('MELGAR','22'),
('MOYOBAMBA','23'),
('NAZCA','12'),
('OCROS','4'),
('OTUZCO','14'),
('OXAPAMPA','20'),
('OYON','16'),
('PALLASCA','4'),
('PARINACOCHAS','7'),
('PASCO','20'),
('PATAZ','14'),
('PAUCAR DEL SARA SARA','7'),
('PISCO','12'),
('PIURA','21'),
('PUNO','22'),
('RECUAY','4'),
('REQUENA','17'),
('RIOJA','23'),
('SAN IGNACIO','8'),
('SAN MARCOS','8'),
('SAN MARTIN','23'),
('SAN MIGUEL','8'),
('SAN ROMÁN','22'),
('SANCHEZ CARRION','14'),
('SANDIA','22'),
('SANTA','4'),
('SANTA CRUZ','8'),
('SANTIAGO DE CHUCO','14'),
('SATIPO','13'),
('SIHUAS','4'),
('TACNA','24'),
('TALARA','21'),
('TAMBOPATA','18'),
('TARMA','13'),
('TAYACAJA','10'),
('TRUJILLO','14'),
('TUMBES','25'),
('URUBAMBA','9'),
('UTCUBAMBA','3'),
('VICTOR FAJARDO','7'),
('VIRÚ','14'),
('YAULI','13'),
('YAUYOS','16');