USE GAF_FACTURACION;

DROP TABLE TMMIGR_NEGO_SUCU;
--
DROP TABLE TMCIER_DATA_PROM_MONT;
DROP TABLE TMCIER_DATA_PLAN;
DROP TABLE TMCIER_DATA_SERV_SUPL;
DROP TABLE TMCIER_DATA_SERV_UNIC;
DROP TABLE TMCIER_DATA_SUCU;
DROP TABLE TMCIER_DATA_NEGO;

-- DROP TABLE TMSUSP_CIER;
DROP TABLE TMSUSP;

-- DROP TABLE TMCORT_CIER;
DROP TABLE TMNEGO_SALD;
DROP TABLE TMNEGO_COME;
DROP TABLE TMNEGO_PROM;
DROP TABLE TMNEGO_SUCU_PROM;
DROP TABLE TMAJUS;


DROP TABLE TMCORT;

DROP TABLE TMCIER_LOGS;

DROP TABLE TMRECI_GLOS;
DROP TABLE TMRECI;
DROP TABLE TMFACT_GLOS;
DROP TABLE TMFACT;
ALTER TABLE TMNEGO_SUCU_SERV_UNIC DROP fk_tmnego_sucu_serv_unic_cier;-- borramos foreing key de cierre y detalla sucursal negocio servicio unico
DROP TABLE TMCIER;

DROP TABLE TMNEGO_SUCU_SERV_SUPL;
DROP TABLE TMNEGO_SUCU_SERV_UNIC;
DROP TABLE TMNEGO_SUCU_PLAN;
DROP TABLE TMNEGO_SUCU;
DROP TABLE TMNEGO_CORR;
DROP TABLE TMMOTI_DESC;
DROP TABLE TMNEGO;
ALTER TABLE TMCLIE DROP fk_tmclie_sucu_fisc;-- borramos foreing key de cliente y sucursal, ya que no puede existe una relacion circular obligatoria
DROP TABLE TMSUCU;

ALTER TABLE TMCLIE DROP fk_tmclie_cont_clie;-- borramos foreing key de representante legal
DROP TABLE TMCONT_CLIE;
DROP TABLE TMCLIE;
DROP TABLE TMTIPO_DOCU;
DROP TABLE TMTIPO_CLIE;

DROP TABLE TMDIST;
DROP TABLE TMPROV;
DROP TABLE TMDEPA;


DROP TABLE TMPLAN;
DROP TABLE TMSERV_SUPL;
DROP TABLE TMSERV_UNIC;
DROP TABLE TMPLAN_MEDI_INST;
DROP TABLE TMPROD;
DROP TABLE TMTIPO_FACT;
DROP TABLE TMMONE_FACT;
DROP TABLE TMPERI_FACT;


--PREFILES
DROP TABLE TMPERF_ITEM_MODU;
DROP TABLE TMITEM_MODU;
DROP TABLE TMMODU;
DROP TABLE TMUSUA;
DROP TABLE TMPERF;

