USE GAF_FACTURACION;

-- DROP TABLE HMSUSP_CIER;
DROP TABLE HMSUSP;

-- DROP TABLE HMCORT_CIER;
DROP TABLE HMNEGO_SALD;
DROP TABLE HMAJUS;
DROP TABLE HMNEGO_PROM;
DROP TABLE HMNEGO_SUCU_PROM;

DROP TABLE HMCORT;

DROP TABLE HMCIER_LOGS;

DROP TABLE HMRECI_GLOS;
DROP TABLE HMRECI;
DROP TABLE HMFACT_GLOS;
DROP TABLE HMFACT;
DROP TABLE HMCIER;

DROP TABLE HMNEGO_SUCU_SERV_SUPL;
DROP TABLE HMNEGO_SUCU_SERV_UNIC;
DROP TABLE HMNEGO_SUCU_PLAN;
DROP TABLE HMNEGO_SUCU;
DROP TABLE HMNEGO;
DROP TABLE HMSUCU;

DROP TABLE HMCONT_CLIE;
DROP TABLE HMCLIE;
DROP TABLE HMTIPO_DOCU;
DROP TABLE HMTIPO_CLIE;

DROP TABLE HMDIST;
DROP TABLE HMPROV;
DROP TABLE HMDEPA;


DROP TABLE HMPLAN;
DROP TABLE HMSERV_SUPL;
DROP TABLE HMSERV_UNIC;
DROP TABLE HMPLAN_MEDI_INST;
DROP TABLE HMPROD;
DROP TABLE HMTIPO_FACT;
DROP TABLE HMMONE_FACT;
DROP TABLE HMPERI_FACT;


DROP TRIGGER TR_HMTIPO_DOCU;
DROP TRIGGER TR_HMTIPO_CLIE;
DROP TRIGGER TR_HMCLIE;
DROP TRIGGER TR_HMCONT_CLIE;
DROP TRIGGER TR_HMDEPA;
DROP TRIGGER TR_HMPROV;
DROP TRIGGER TR_HMDIST;
DROP TRIGGER TR_HMSUCU;
DROP TRIGGER TR_HMPERI_FACT;
DROP TRIGGER TR_HMTIPO_FACT;
DROP TRIGGER TR_HMMONE_FACT;
DROP TRIGGER TR_HMPROD;
DROP TRIGGER TR_HMPLAN_MEDI_INST;
DROP TRIGGER TR_HMPLAN;
DROP TRIGGER TR_HMSERV_SUPL;
DROP TRIGGER TR_HMSERV_UNIC;
DROP TRIGGER TR_HMNEGO;
DROP TRIGGER TR_HMNEGO_SUCU;
DROP TRIGGER TR_HMNEGO_SUCU_PLAN;
DROP TRIGGER TR_HMNEGO_SUCU_SERV_SUPL;
DROP TRIGGER TR_HMNEGO_SUCU_SERV_UNIC;
DROP TRIGGER TR_HMCIER;
DROP TRIGGER TR_HMCIER_LOGS;
DROP TRIGGER TR_HMNEGO_SALD;
DROP TRIGGER TR_HMAJUS;
DROP TRIGGER TR_HMNEGO_PROM;
DROP TRIGGER TR_HMNEGO_SUCU_PROM;
DROP TRIGGER TR_HMRECI;
DROP TRIGGER TR_HMRECI_GLOS;
DROP TRIGGER TR_HMFACT;
DROP TRIGGER TR_HMFACT_GLOS;
DROP TRIGGER TR_HMCORT;
DROP TRIGGER TR_HMSUSP;